ALTER TABLE products ADD COLUMN reference VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN category VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN brand VARCHAR(255) NOT NULL DEFAULT '';
